"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { Check, X, Loader2 } from "lucide-react";
import { checkSlugAvailability } from "./actions";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export function SlugField({
  value,
  onChange,
  title,
  excludeLinkId,
}: {
  value: string;
  onChange: (slug: string) => void;
  title: string;
  excludeLinkId?: string;
}) {
  const [checking, setChecking] = useState(false);
  const [available, setAvailable] = useState<boolean | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(true);
  const timerRef = useRef<ReturnType<typeof setTimeout>>(undefined);
  const lastCheckedRef = useRef("");

  // Auto-generate from title if user hasn't manually edited
  useEffect(() => {
    if (autoGenerated && title) {
      const slug = slugify(title);
      if (slug.length >= 3) {
        onChange(slug);
      } else {
        onChange("");
      }
    }
  }, [title, autoGenerated, onChange]);

  // Debounced availability check
  const checkAvailability = useCallback(
    (slug: string) => {
      if (timerRef.current) clearTimeout(timerRef.current);
      if (!slug || slug.length < 3 || !/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(slug)) {
        setAvailable(null);
        setChecking(false);
        return;
      }
      if (slug === lastCheckedRef.current) return;
      setChecking(true);
      timerRef.current = setTimeout(async () => {
        const result = await checkSlugAvailability(slug, excludeLinkId);
        lastCheckedRef.current = slug;
        setAvailable(result.available);
        setChecking(false);
      }, 500);
    },
    [excludeLinkId]
  );

  useEffect(() => {
    checkAvailability(value);
    return () => { if (timerRef.current) clearTimeout(timerRef.current); };
  }, [value, checkAvailability]);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const raw = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "");
    setAutoGenerated(false);
    onChange(raw);
  }

  function handleClear() {
    onChange("");
    setAutoGenerated(false);
    setAvailable(null);
  }

  const isValid = value.length === 0 || (value.length >= 3 && /^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(value));
  const showError = value.length > 0 && !isValid;
  const showTaken = value.length >= 3 && isValid && available === false;
  const showOk = value.length >= 3 && isValid && available === true;

  return (
    <div className="mb-5">
      <label className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wider text-neutral-500">
        URL personnalisee (optionnel)
      </label>
      <div className="flex items-center gap-2">
        <div className="relative flex-1">
          <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[11px] text-neutral-300">
            reel.sad-pictures.com/s/
          </span>
          <input
            type="text"
            value={value}
            onChange={handleChange}
            placeholder="mon-lien"
            className={`w-full rounded-lg border bg-white py-2 pr-8 text-[13px] text-neutral-900 outline-none transition-colors placeholder:text-neutral-300 focus:border-neutral-400 ${
              showTaken ? "border-red-300" : showOk ? "border-emerald-300" : "border-neutral-200"
            }`}
            style={{ paddingLeft: 170 }}
          />
          <div className="absolute right-2.5 top-1/2 -translate-y-1/2">
            {checking && <Loader2 className="h-3.5 w-3.5 animate-spin text-neutral-300" />}
            {!checking && showOk && <Check className="h-3.5 w-3.5 text-emerald-500" />}
            {!checking && showTaken && <X className="h-3.5 w-3.5 text-red-500" />}
          </div>
        </div>
        {value && (
          <button
            type="button"
            onClick={handleClear}
            className="shrink-0 text-[11px] text-neutral-400 transition-colors hover:text-neutral-600"
          >
            Effacer
          </button>
        )}
      </div>
      {showError && (
        <p className="mt-1 text-[11px] text-red-500">
          Min 3 caracteres, lettres minuscules, chiffres et tirets (pas au debut/fin)
        </p>
      )}
      {showTaken && (
        <p className="mt-1 text-[11px] text-red-500">Ce slug est deja utilise</p>
      )}
      {showOk && (
        <p className="mt-1 text-[11px] text-emerald-600">
          reel.sad-pictures.com/s/{value}
        </p>
      )}
    </div>
  );
}
